   <?php
    // Template Name: Política de cookies
    get_header();
    ?>

   <!-- Start CookieYes cookie policy -->
   <style>
       a.cky-banner-element {
           padding: 8px 30px;
           background: #f8f9fa;
           color: #858a8f;
           border: 1px solid #dee2e6;
           box-sizing: border-box;
           border-radius: 2px;
           cursor: pointer
       }
   </style>

   <div class="p-10 mt-[100px]">
       <h1 class="cookie-policy-h1">Cookie Policy</h1>
       <div class="cookie-policy-date-container">
           <p>Effective date: September 18, 2025</p>
           <p>Last updated: September 18, 2025</p>
       </div>&nbsp;<h2>O que são cookies?</h2>
       <div class="cookie-policy-p">
           <p>Esta Política de Cookies explica o que são cookies, como os utilizamos, os tipos de cookies que usamos (ou seja, as informações que coletamos usando cookies e como essas informações são utilizadas) e como gerenciar as suas configurações de cookies.</p>
           <p>Cookies são pequenos arquivos de texto usados para armazenar pequenas informações. Eles são armazenados em seu dispositivo quando um site é carregado no seu navegador. Esses cookies ajudam a garantir que o site funcione corretamente, aumentam a segurança, proporcionam uma melhor experiência ao usuário e permitem analisar o desempenho para identificar o que funciona e onde melhorias são necessárias.</p>
       </div>&nbsp;<h2>Como usamos os cookies?</h2>
       <div class="cookie-policy-p">
           <p>Como a maioria dos serviços online, nosso site utiliza cookies próprios (first-party) e de terceiros (third-party) para diferentes finalidades. Os cookies próprios são principalmente necessários para que o site funcione corretamente e <strong>não coletam dados pessoais identificáveis</strong>.</p>
           <p>Os cookies de terceiros usados em nosso site têm como principal função nos ajudar a entender como o site está performando, acompanhar como você interage com ele, manter nossos serviços seguros, exibir anúncios relevantes e melhorar sua experiência geral de uso, além de aumentar a velocidade das suas futuras interações com o nosso site.</p>
       </div>&nbsp;<h2>Tipos de cookies que usamos</h2>
       <div class="cky-audit-table-element"></div>&nbsp;<h2 style="margin-bottom: 20px">Manage cookie preferences</h2><a class="cky-banner-element">Consent Preferences</a><br />
       <div>
           <p>Você pode modificar suas configurações de cookies a qualquer momento clicando no botão <strong>‘Preferências de Consentimento’</strong> acima. Isso permitirá que você volte ao banner de consentimento de cookies e atualize suas preferências ou retire seu consentimento imediatamente.</p>
           <p>Além disso, diferentes navegadores oferecem métodos variados para bloquear e excluir os cookies usados pelos sites. Você pode ajustar as configurações do seu navegador para bloquear ou excluir cookies. Abaixo estão links para documentos de suporte sobre como gerenciar e excluir cookies nos principais navegadores:</p>
           <ol>
               <li data-list="bullet"><span class="ql-ui" contenteditable="false"></span><strong>Chrome:</strong> <a href="https://support.google.com/accounts/answer/32050" rel="noopener noreferrer" target="_blank">https://support.google.com/accounts/answer/32050</a></li>
               <li data-list="bullet"><span class="ql-ui" contenteditable="false"></span><strong>Safari:</strong> <a href="https://support.apple.com/en-in/guide/safari/sfri11471/mac" rel="noopener noreferrer" target="_blank">https://support.apple.com/en-in/guide/safari/sfri11471/mac</a></li>
               <li data-list="bullet"><span class="ql-ui" contenteditable="false"></span><strong>Firefox:</strong> <a href="https://support.mozilla.org/en-US/kb/clear-cookies-and-site-data-firefox?redirectslug=delete-cookies-remove-info-websites-stored&amp;redirectlocale=en-US" rel="noopener noreferrer" target="_blank">https://support.mozilla.org/en-US/kb/clear-cookies-and-site-data-firefox?redirectslug=delete-cookies-remove-info-websites-stored&amp;redirectlocale=en-US</a></li>
               <li data-list="bullet"><span class="ql-ui" contenteditable="false"></span><strong>Internet Explorer:</strong> <a href="https://support.microsoft.com/en-us/topic/how-to-delete-cookie-files-in-internet-explorer-bca9446f-d873-78de-77ba-d42645fa52fc" rel="noopener noreferrer" target="_blank">https://support.microsoft.com/en-us/topic/how-to-delete-cookie-files-in-internet-explorer-bca9446f-d873-78de-77ba-d42645fa52fc</a></li>
           </ol>
           <p>Se você estiver usando outro navegador, consulte a documentação oficial de suporte correspondente.</p>
       </div>&nbsp;<p class="cookie-policy-p"> Cookie Policy generated by <a target="_blank" rel="noopener noreferrer" href="https://www.cookieyes.com/?utm_source=CP&utm_medium=footer&utm_campaign=UW">CookieYes - Cookie Policy Generator</a></p>

   </div>
   <!-- End CookieYes cookie policy -->

   <?php
    get_footer();
    ?>